"use client";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import type { Hex } from "viem";
import { useAccount, usePublicClient, useSignMessage } from "wagmi";
import { SiweMessage } from "siwe";
import { Button } from "./button";
import { useQuery } from "@tanstack/react-query";
import { signIn, useSession } from "next-auth/react";
import { parseErc6492Signature } from "viem/experimental";
// Function to fetch nonce from the backend
const fetchNonce: () => Promise<string> = async () => {
  const response = await fetch("/api/nonce");
  if (!response.ok) {
    throw new Error("Network response was not ok");
  }
  const data = (await response.json()) as { nonce: string };
  return data.nonce ?? "";
};

export function SignInWithEthereum() {
  const [signature, setSignature] = useState<Hex | undefined>(undefined);
  const [valid, setValid] = useState<boolean | undefined>(undefined);
  const client = usePublicClient();

  const { signMessageAsync } = useSignMessage({
    mutation: {
      onSuccess: async (sig) => {
        setSignature(parseErc6492Signature(sig).signature);
        await signIn("credentials", {
          message: JSON.stringify(message),
          redirect: false,
          signature: parseErc6492Signature(sig).signature,
          callbackUrl: "/web3",
        });
      },
    },
  });
  const account = useAccount();

  const { data: nonce } = useQuery({
    queryKey: ["nonce"],
    queryFn: fetchNonce,
  });

  const message = useMemo(() => {
    if (!account.address) return;
    return new SiweMessage({
      domain: document.location.host,
      address: account.address,
      chainId: account.chainId,
      uri: document.location.origin,
      version: "1",
      statement: "Honefolio Smart Wallet SIWE Example",
      nonce: nonce ?? "", // replace with nonce generated by your backend
    });
  }, [account.address]);

  const checkValid = useCallback(async () => {
    if (!signature || !account.address || !client) return;
    const isValid = await client.verifyMessage({
      address: account.address,
      message: message?.prepareMessage() ?? "",
      signature: parseErc6492Signature(signature).signature,
    });
    setValid(isValid);
  }, [signature, account]);

  useEffect(() => {
    checkValid().catch(console.error);
  }, [signature, account]);

  const promptToSign = async () => {
    await signMessageAsync({ message: message?.prepareMessage() ?? "" });
  };
  return (
    <>
      <Button onClick={promptToSign}>Sign In with Ethereum</Button>
      {signature && <p className="break-all">Signature: {signature}</p>}
      {valid !== undefined && <p>Is valid: {valid.toString()}</p>}
    </>
  );
}
